from .free_models import NODE_CLASS_MAPPINGS as _FREE_C, NODE_DISPLAY_NAME_MAPPINGS as _FREE_D
from .sage3_attention import NODE_CLASS_MAPPINGS as _SAGE_C, NODE_DISPLAY_NAME_MAPPINGS as _SAGE_D
from .h3_resolution_selector import NODE_CLASS_MAPPINGS as _RES_C, NODE_DISPLAY_NAME_MAPPINGS as _RES_D

NODE_CLASS_MAPPINGS = {**_FREE_C, **_SAGE_C, **_RES_C}
NODE_DISPLAY_NAME_MAPPINGS = {**_FREE_D, **_SAGE_D, **_RES_D}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
